'use client';

import { motion, useScroll, useTransform, useInView, AnimatePresence } from 'framer-motion';
import { Download, Flame, Ghost, Medal, MessageSquare, Sparkles, Trophy, Zap } from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';

const taglines = ['Because not everyone became a CEO at 17.', 'Network with failure.', 'Celebrate poor decisions.', 'Professionally underqualified.', 'Where unfinished projects become achievements.', "Your parents don't need to see this."];
const badges = ['🏆 Missed 12 Deadlines', '🏆 Bought 47 Courses, Finished 0', '🏆 Started Learning Python 14 Times', '🏆 Opened Gym Membership, Never Returned'];
const notifications = ['Ali just abandoned another side project.', 'Sarah watched 83 tutorials without building anything.', 'Ahmed forgot his own password again.', 'Maya pivoted from SaaS to crying in Notion.'];
const skills = [['Procrastination', 100], ['Overthinking', 95], ['Meeting Deadlines', 7], ['Watching Tutorials', 100], ['Finishing Projects', 20]] as const;
const feed = ['Ali proudly abandoned his 23rd side project today.', 'Sarah spent 8 hours customizing VS Code instead of coding.', 'Ahmed renamed a folder and called it a startup.', 'Nora shipped a landing page for an app that does not exist.'];
const achievements = ['Watched 100 Tutorials', 'Refactored Instead Of Shipping', 'Bought Another Domain', 'Changed Career Path Again', 'Spent 6 Hours Fixing A Missing Semicolon', 'Created A To-Do List To Avoid Doing Tasks'];

function Counter({ value }: { value: number }) {
  const ref = useRef(null); const seen = useInView(ref, { once: true }); const [n, setN] = useState(0);
  useEffect(() => { if (!seen) return; let f=0; const id=setInterval(()=>{f+=1; setN(Math.round(value*(1-Math.pow(.92,f)))); if(f>70){setN(value); clearInterval(id)}},16); return()=>clearInterval(id); }, [seen, value]);
  return <span ref={ref}>{n.toLocaleString()}</span>;
}

function Section({ children, className='' }: { children: React.ReactNode; className?: string }) { return <section className={`mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8 ${className}`}>{children}</section>; }

export default function ReverseLinkedIn() {
  const [tag, setTag] = useState(0), [score, setScore] = useState(9437), [toast, setToast] = useState(''), [logoClicks, setLogoClicks] = useState(0), [recruiter, setRecruiter] = useState(false);
  const [profile, setProfile] = useState({ name: 'Mohammad Ali', regret: 'Buying premium Notion templates', projects: 52 });
  const { scrollYProgress } = useScroll(); const heroY = useTransform(scrollYProgress, [0, .35], [0, -120]);
  const particles = useMemo(() => Array.from({ length: 42 }, (_, i) => ({ id:i, x: Math.random()*100, y: Math.random()*100, d: 3+Math.random()*7 })), []);
  useEffect(() => { const t=setInterval(()=>setTag(v=>(v+1)%taglines.length),2200); const r=setInterval(()=>setRecruiter(true),9000); return()=>{clearInterval(t); clearInterval(r)} }, []);
  useEffect(() => { let seq=''; const onKey=(e:KeyboardEvent)=>{ seq=(seq+e.key).slice(-90); if(seq.toLowerCase().includes('ceo')) setToast('Nice try.'); if(seq.endsWith('ArrowUpArrowUpArrowDownArrowDownArrowLeftArrowRightArrowLeftArrowRightba')) setToast('Ultimate Disappointment Mode unlocked. The bar was already low.'); }; window.addEventListener('keydown',onKey); return()=>window.removeEventListener('keydown',onKey); }, []);
  function calc() { const next = Math.round(7000 + profile.projects * 83 + Math.random()*1800); setScore(next); setToast('Failure Score recalibrated. Somehow worse than expected.'); }
  function logo() { const c=logoClicks+1; setLogoClicks(c); if(c>=5) setToast('Achievement Unlocked: Unemployed Visionary'); }
  function resume() { const text = `${profile.name}\nProfessional Underachiever\n\nExperience\n2024-Present Senior Procrastination Engineer\n\nAchievements\n- Missed 43 deadlines\n- Started ${profile.projects} projects\n- Finished 4\n- Watched 300 hours of tutorials\n\nReferences\n- My disappointed teacher\n- My unfinished GitHub repositories`; const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'})); a.download='failure-resume.txt'; a.click(); }
  return <main className="noise relative min-h-screen overflow-hidden mesh">
    <div className="fixed inset-0 -z-10 bg-ink" />{particles.map(p=><motion.span key={p.id} className="fixed -z-10 h-1 w-1 rounded-full bg-white/40" style={{left:`${p.x}%`,top:`${p.y}%`}} animate={{y:[0,-35,0], opacity:[.15,.8,.15]}} transition={{duration:p.d, repeat:Infinity}} />)}
    <nav className="sticky top-0 z-40 border-b border-white/10 bg-ink/55 backdrop-blur-2xl"><Section className="flex h-16 items-center justify-between"><button onClick={logo} className="group flex items-center gap-3 font-black tracking-tight"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-white text-ink transition group-hover:rotate-6">R</span>Reverse LinkedIn</button><a href="#builder" className="rounded-full bg-white px-5 py-2 text-sm font-bold text-ink hover:bg-acid">Create profile</a></Section></nav>
    <Section className="relative grid min-h-[calc(100vh-4rem)] items-center gap-10 py-16 lg:grid-cols-[1.08fr_.92fr]"><motion.div style={{y:heroY}}><div className="mb-5 inline-flex rounded-full border border-acid/30 bg-acid/10 px-4 py-2 text-sm text-acid"><Sparkles className="mr-2 h-4 w-4"/> {taglines[tag]}</div><h1 className="max-w-4xl text-5xl font-black leading-[.92] tracking-[-.06em] sm:text-7xl lg:text-8xl">Your failures deserve recognition too.</h1><p className="mt-6 max-w-2xl text-lg text-white/70 sm:text-2xl">Tired of fake success stories? Create a profile that finally reflects reality.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#builder" className="rounded-2xl bg-acid px-7 py-4 text-center font-black text-ink shadow-glow transition hover:-translate-y-1">Create My Failure Profile</a><button onClick={calc} className="rounded-2xl border border-white/15 bg-white/10 px-7 py-4 font-black backdrop-blur transition hover:-translate-y-1">Calculate My Failure Score</button></div></motion.div><div className="relative h-[560px]">{badges.map((b,i)=><motion.div key={b} className="glass absolute rounded-3xl px-5 py-4 font-bold" style={{left:[0,28,8,42][i]+'%', top:[6,24,50,70][i]+'%'}} animate={{y:[0,-18,0], rotate:[-2,2,-2]}} transition={{duration:5+i, repeat:Infinity}}>{b}</motion.div>)}{notifications.map((n,i)=><motion.div key={n} className="glass absolute right-0 max-w-xs rounded-3xl p-4 text-sm text-white/80" style={{top:[14,38,62,82][i]+'%'}} initial={{x:80,opacity:0}} animate={{x:0,opacity:1}} transition={{delay:i*.4}}><MessageSquare className="mb-2 h-4 w-4 text-blush"/>{n}</motion.div>)}</div></Section>
    <Section className="grid gap-6 py-14 sm:grid-cols-3"><Stat label="Abandoned projects celebrated" v={128403}/><Stat label="Tutorials watched instead of working" v={904221}/><Stat label="Fake recruiters concerned" v={37}/></Section>
    <Section className="grid gap-6 py-16 lg:grid-cols-2" id="builder"><Panel title="Failure Profile Builder"><div className="grid gap-3 sm:grid-cols-2"><Input label="Name" value={profile.name} onChange={v=>setProfile({...profile,name:v})}/><Input label="Age" value="29-ish emotionally"/><Input label="Biggest Regret" value={profile.regret} onChange={v=>setProfile({...profile,regret:v})}/><Input label="Unfinished Projects" value={String(profile.projects)} onChange={v=>setProfile({...profile,projects:+v||0})}/></div><div className="mt-6 rounded-3xl bg-gradient-to-br from-white/15 to-white/5 p-5"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-3xl bg-plasma text-3xl">😬</div><div><h3 className="text-2xl font-black">{profile.name}</h3><p className="text-white/60">Founder, ComingSoon.ai (coming soon)</p></div></div><p className="mt-4 text-white/70">Biggest regret: {profile.regret}. Started a startup that lasted 4 hours and learned 3% of 17 programming languages.</p></div></Panel><Panel title="Skills Endorsed By People Avoiding You">{skills.map(([s,v])=><div key={s} className="mb-5"><div className="mb-2 flex justify-between text-sm"><span>{s}</span><b>{v}%</b></div><div className="h-3 rounded-full bg-white/10"><motion.div className="progress h-full rounded-full" initial={{width:0}} whileInView={{width:`${v}%`}} viewport={{once:true}} /></div></div>)}</Panel></Section>
    <Section className="grid gap-6 py-16 lg:grid-cols-[.8fr_1.2fr]"><Panel title="Failure Score Calculator"><p className="text-white/60">Projects started, courses abandoned, tabs open, and times you said “I'll do it tomorrow” are converted into investor-grade shame.</p><div className="my-7 text-6xl font-black text-acid"><Counter value={score}/></div><p className="font-bold">Top 1% globally · Elite Procrastinator · Chaos Engineer (Not the Good Kind)</p><button onClick={calc} className="mt-6 w-full rounded-2xl bg-white py-4 font-black text-ink">Recalculate my damage</button></Panel><Panel title="Failure Feed">{feed.map((f,i)=><motion.article key={f} className="mb-4 rounded-3xl border border-white/10 bg-white/5 p-5 transition hover:-translate-y-1 hover:bg-white/10" whileHover={{scale:1.01}}><p className="font-semibold">{f}</p><div className="mt-4 flex flex-wrap gap-2">{['Relatable','Been There','Respectfully Terrible','Peak Performance'].map(r=><button key={r} className="rounded-full bg-white/10 px-3 py-1 text-xs hover:bg-acid hover:text-ink">{r}</button>)}</div></motion.article>)}</Panel></Section>
    <Section className="py-16"><div className="mb-8 flex items-end justify-between gap-4"><div><p className="text-acid">Achievement System</p><h2 className="text-4xl font-black tracking-tight">Absurdly premium badges for deeply preventable behavior.</h2></div><button onClick={resume} className="hidden rounded-2xl bg-blush px-5 py-3 font-black sm:flex"><Download className="mr-2"/>AI Failure Resume</button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{achievements.map((a,i)=><motion.div key={a} className="glass rounded-3xl p-6" whileHover={{y:-8, rotate:i%2?1:-1}}><Trophy className="mb-4 text-acid"/><h3 className="text-xl font-black">🏆 {a}</h3><p className="mt-2 text-sm text-white/55">Endorsed by 14 managers who stopped replying.</p></motion.div>)}</div></Section>
    <Section className="py-16"><Panel title="Leaderboard"><div className="grid gap-3 md:grid-cols-5">{['Most Abandoned Projects','Largest Tutorial Collection','Biggest Failure Score','Most Browser Tabs Open','Longest Coming Soon Project'].map((l,i)=><div key={l} className="rounded-3xl bg-white/5 p-4"><Medal className="mb-3 text-blush"/><b>{l}</b><p className="mt-2 text-3xl font-black"><Counter value={[481,1204,9999,312,7][i]}/></p></div>)}</div></Panel></Section>
    <footer className="border-t border-white/10 py-10 text-center text-white/50">Reverse LinkedIn © 2026 — A billion-dollar startup accidentally celebrating incompetence.</footer>
    <AnimatePresence>{toast && <motion.div className="fixed bottom-5 left-1/2 z-50 -translate-x-1/2 rounded-2xl border border-acid/30 bg-ink/90 px-5 py-4 text-acid shadow-glow backdrop-blur" initial={{y:80,opacity:0}} animate={{y:0,opacity:1}} exit={{y:80,opacity:0}} onAnimationComplete={()=>setTimeout(()=>setToast(''),2600)}><Zap className="mr-2 inline"/>{toast}</motion.div>}</AnimatePresence>
    <AnimatePresence>{recruiter && <motion.div className="fixed right-4 top-24 z-50 max-w-sm rounded-3xl border border-white/10 bg-white/10 p-5 shadow-glow backdrop-blur-2xl" initial={{x:420,opacity:0}} animate={{x:0,opacity:1}} exit={{x:420,opacity:0}}><button className="float-right" onClick={()=>setRecruiter(false)}>×</button><Ghost className="mb-3 text-blush"/><h3 className="font-black">Recruiter message</h3><p className="mt-2 text-white/75">“Your lack of qualifications perfectly matches our requirements.”</p></motion.div>}</AnimatePresence>
  </main>;
}
function Stat({label,v}:{label:string;v:number}){return <div className="glass rounded-3xl p-6"><Flame className="mb-3 text-blush"/><div className="text-4xl font-black"><Counter value={v}/></div><p className="mt-2 text-white/55">{label}</p></div>}
function Panel({title, children}:{title:string;children:React.ReactNode}){return <motion.div className="glass rounded-[2rem] p-5 sm:p-8" initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true, margin:'-80px'}}><h2 className="mb-6 text-2xl font-black tracking-tight sm:text-3xl">{title}</h2>{children}</motion.div>}
function Input({label,value,onChange}:{label:string;value:string;onChange?:(v:string)=>void}){return <label className="block"><span className="mb-2 block text-sm text-white/55">{label}</span><input value={value} onChange={e=>onChange?.(e.target.value)} className="w-full rounded-2xl border border-white/10 bg-white/10 px-4 py-3 outline-none transition focus:border-acid focus:ring-4 focus:ring-acid/10" /></label>}
